### ISSUE TITLE
Run in background permission

### ISSUE THREAD

**Issue by d13r** [alex7kom/Copy-Page-URL#6]
Hi,

First thanks for this, it's a useful extension for copying the URL of a page running in application mode.

My question is why does it need run in background permission? I have many other extensions, and the only other one that asks for that permission is Google Hangouts. I can't think of any functionality this extension provides that would require that permission (though I'm not an expert on Chrome permissions), and it's not mentioned anywhere in the Store page or README - which made me immediately suspicious of it. I strongly considered removing it in case it was doing something malicious, but then I checked the code and I can't see it doing anything much.

Thanks
Dave

**Comment by alex7kom** [comment]
Thank you for reporting this! I'll review the code and permissions, and consider removing `"background"`. As far as I remember the extension didn't work without it when I wrote it but it was about 3 years ago.

**Comment by d13r** [comment]
Thanks 😃
