### ISSUE TITLE
Duration of OK Confirmation

### ISSUE THREAD

**Issue by smaragdus** [alex7kom/Copy-Page-URL#7]
Hello,

I think that OK confirmation that a page URL has been copied lingers for too long on tool bar button of [Copy Page URL](https://chrome.google.com/webstore/detail/copy-page-url/dobnehimlklapeengfdlhdkpijhjdkag) when copying is executed via the tool bar button. It seems that this OK stays for about 3 seconds- I copy a page URL, close the tab, go to copying another tab and OK is still there. This does not prevent me from copying another page URL while OK is still on the tool bar button but for me 3 seconds is too long.

My suggestion:

- either add an option in extension options for how long OK should stay on tool bar button (in seconds)
- or make OK appear for a 1 second (at least for me 1 second is enough)

I suppose that the first option would be a better solution as the users would be able to specify the duration to their liking,

Anyway, [Copy Page URL](https://github.com/alex7kom/Copy-Page-URL) is very a useful extension for copying of page URLs via a single click, thanks for maintaining this project.

Regards

**Comment by alex7kom** [comment]
Thanks for the suggestions!

There is no reason this duration couldn't be smaller, it was chosen rather arbitrary after all. I'd like to avoid introducing a new option, however, because every option induces additional maintenance costs.

I'd like to add another suggestion. You have mentioned that you'd like OK to disappear when you close the tab or go to another tab. And it's possible to hide OK immediately after the active tab is changed.

What do you think about this?

**Comment by smaragdus** [comment]
@alex7kom 

Thanks for the immediate response.

> There is no reason this duration couldn't be smaller, it was chosen rather arbitrary after all.

Perhaps I am used to shorter duration of text badge shown on the button in the tool bar. I do not know what duration other users would prefer. At least for me OK badge appearing for a second would be enough. What do you think?

> I'd like to avoid introducing a new option, however, because every option induces additional maintenance costs.

I understand your attitude.

> I'd like to add another suggestion. You have mentioned that you'd like OK to disappear when you close the tab or go to another tab. And it's possible to hide OK immediately after the active tab is changed.
> 
> What do you think about this?

It would be fine but wouldn't this over-complicate the code?

Anyway, **Copy Page URL** is easy and handy to use in its current form. I also use other similar copy extensions like for example **Copy Cat** ([Chrome Web Store](https://chrome.google.com/webstore/detail/copy-cat-quick-copy-title/andlmjmbnlaamloflnelcafcnkiplhkc), [GitHub](https://github.com/kiichi/QuickCopyTitleAndURL/)), screen:

![Copy Cat 1 4 2 - 2020-01-13 - 002](https://user-images.githubusercontent.com/9025757/72677056-d3c06080-3aa0-11ea-81f2-70084250de9c.png)

to perform different copy operations (HTML, Markdown, BBCode) but for fast single click page URL copy **Copy Page URL** is just perfect, You may choose to diminish the time the text badge is shown, you may leave as it is- it is just fine, Feel free to also close this issue.

Regards

**Comment by alex7kom** [comment]
> Perhaps I am used to shorter duration of text badge shown on the button in the tool bar. I do not know what duration other users would prefer. At least for me OK badge appearing for a second would be enough. What do you think?

I'm sorry, I probably botched the meaning in my writing. Decreasing the duration is perfectly fine.

> It would be fine but wouldn't this over-complicate the code?

Not at all.

Anyway, both changes are implemented and the new version should be live on Chrome Store soon.
https://github.com/alex7kom/Copy-Page-URL/blob/master/CHANGELOG.md#07

**Comment by smaragdus** [comment]
@alex7kom 

> Anyway, both changes are implemented and the new version should be live on Chrome Store soon.

This was really quick, however the latest version (**0.7**) hasn't yet landed on [Chrome Web Store](https://chrome.google.com/webstore/detail/copy-page-url/dobnehimlklapeengfdlhdkpijhjdkag), as far as I know they manually review updates so the update process is a bit slower. When I get the update I will have a look and if everything is fine I will close this issue. Thank you for the new release!

**Comment by alex7kom** [comment]
Unfortunately, the new version was rejected by Chrome Web Store citing "Spam and Placement in the Store" of [Program Policies](https://developer.chrome.com/webstore/program_policies). I've asked for assistance and right now I'm waiting for a response from the support.

**Comment by smaragdus** [comment]
@alex7kom 

This is very unpleasant. I hope that you will get a real response, not some canned one. I had a look at [Developer Program Policies](https://developer.chrome.com/webstore/program_policies) and this is total censorship to me. Google is really evil, as is Firefox, the difference between these two is just the size and the scope of outreach, The situation with the major browsers (Chrome and Firefox) is disturbing and depressing- just have a look at [Manifest V3](https://docs.google.com/document/d/1nPu6Wy4LWR66EFLeYInl3NzzhHzc-qnk4w4PX-0XMw8/edit#heading=h.5ottncv8stov) if you haven't yet to see what is coming.

**Comment by alex7kom** [comment]
@smaragdus 

The Chrome Web Store team has resolved the situation and the new version is available now, please check it out!

**Comment by smaragdus** [comment]
@alex7kom 

Excellent news! I got version 0.7 through the store. It works as expected (OK badge disappears the moment I close the copied tab) and I really think that 1 second duration of OK badge is better.

Once again, thank you very much for the very quick response and implementation of my suggestion. It would be great if more developers are as helpful and responsive as you!

All the best to you and all your projects!

**Comment by smaragdus** [comment]
I am closing this issue, thanks.
